# Generated by Django 3.2.4 on 2021-08-15 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelayStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_status', models.TextField(default='False')),
                ('button_status', models.TextField(default='True')),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TextField(default='')),
                ('schedule_interval', models.TextField(default='')),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(default='00:00:00', null=True)),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_schedule', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
    ]
