# Generated by Django 3.2.4 on 2021-08-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    def insert_data(apps,schema_editior):
        RelayStatus = apps.get_model('schedule', 'RelayStatus')
        relay_status = RelayStatus(pk=1,schedule_status='False',button_status='False',gpio_pin=14)
        relay_status.save()
        relay_status = RelayStatus(pk=2,schedule_status='False',button_status='False',gpio_pin=15)
        relay_status.save()
        relay_status = RelayStatus(pk=3,schedule_status='False',button_status='False',gpio_pin=23)
        relay_status.save()
        relay_status = RelayStatus(pk=4,schedule_status='False',button_status='False',gpio_pin=18)
        relay_status.save()
        relay_status = RelayStatus(pk=5,schedule_status='False',button_status='False',gpio_pin=24)
        relay_status.save()

    operations = [
        migrations.RunPython(insert_data)
    ]
