# Generated by Django 3.2.5 on 2021-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210813_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
    ]
