# Generated by Django 3.2.4 on 2021-08-13 20:03

from datetime import datetime
from django.db import migrations

from climate.models import ClimateData, ClimateValues, Exhaust
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
    ]

    def insert_data(apps,schema_editior):
        Exhaust = apps.get_model('climate', 'Exhaust')
        exhaust = Exhaust(pk=1,job_id='button_relay_job_id_2',status='False',automation_status='True')
        exhaust.save()
        exhaust = Exhaust(pk=2,job_id='button_relay_job_id_3',status='False',automation_status='True')
        exhaust.save()
        exhaust = Exhaust(pk=3,job_id='button_relay_job_id_4',status='False',automation_status='True')
        exhaust.save()
        ClimateData = apps.get_model('climate', 'climatedata')
        climate_data = ClimateData(pk=1,humidity=0, temp=0, vpd=0, co2=0)
        climate_data.save()
        ClimateValues = apps.get_model('climate', 'climatevalues')
        climate_value = ClimateValues(pk=1,humidity_value=1, buffer_value=10, temp_value=1, co2_value=1, co2_buffer_value=100, start_time=datetime.now(), end_time=datetime.now())
        climate_value.save()
        climate_value = ClimateValues(pk=2,humidity_value=1, buffer_value=10, temp_value=1, co2_value=1, co2_buffer_value=100, start_time=datetime.now(), end_time=datetime.now())
        climate_value.save()

    operations = [
        migrations.RunPython(insert_data)
    ]
